[world]
name = "Crossword"
description = "Crossword Clash game on Starknet"
seed = "crossword_v2"

# [world.socials]
# x = "https://x.com/ohayo_dojo"
# discord = "https://discord.gg/FB2wR6uF"
# github = "https://github.com/dojoengine/dojo-starter"
# telegram = "https://t.me/dojoengine"

[namespace]
default = "crossword"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"


[writers]
"crossword" = ["crossword-actions"]
