// Word -> emoji mapping for crossword clues
// Covers ALL words in our puzzle grids for rich hint display
const WORD_EMOJI_MAP: Record<string, string> = {
  // ── 3-letter words ────────────────────────────────────────────
  ACE: '🃏', ACT: '🎭', ADD: '➕', AGE: '👴', AGO: '⏪',
  AID: '🩹', AIM: '🎯', AIR: '💨', ALL: '💯', AND: '🤝',
  ANT: '🐜', ANY: '❓', APE: '🦍', ARC: '🌈', ARE: '👉',
  ARK: '🚢', ARM: '💪', ART: '🎨', ASK: '❓', ATE: '😋',
  AWE: '😲', AXE: '🪓', BAD: '👎', BAG: '👜', BAN: '🚫',
  BAR: '🍺', BAT: '🦇', BED: '🛏️', BET: '🎰', BIG: '🐘',
  BIT: '💾', BOW: '🎀', BOX: '📦', BOY: '👦', BUD: '🌱',
  BUG: '🐛', BUS: '🚌', BUT: '☝️', BUY: '🛒', CAB: '🚕',
  CAN: '🥫', CAP: '🧢', CAR: '🚗', CAT: '🐱', COP: '👮',
  COW: '🐄', CRY: '😢', CUP: '☕', CUT: '✂️', DAD: '👨',
  DAY: '☀️', DID: '✅', DIG: '⛏️', DIP: '🫕', DOG: '🐕',
  DOT: '⚫', DRY: '🏜️', DUG: '⛏️', EAR: '👂', EAT: '🍽️',
  EGG: '🥚', END: '🏁', ERA: '📜', EVE: '🌙', EYE: '👁️',
  FAN: '🌀', FAR: '🔭', FAT: '🍔', FED: '🍼', FEW: '🤏',
  FIG: '🫐', FIN: '🦈', FIT: '💪', FIX: '🔧', FLY: '✈️',
  FOG: '🌫️', FOR: '➡️', FOX: '🦊', FUN: '🎉', FUR: '🧣',
  GAP: '🕳️', GAS: '⛽', GET: '🤲', GOD: '⛪', GOT: '✅',
  GUM: '🫧', GUN: '🔫', GUY: '🧑', GYM: '🏋️',
  HAD: '📌', HAM: '🥩', HAS: '📌', HAT: '🎩', HER: '👩',
  HID: '🙈', HIM: '👨', HIP: '🦴', HIS: '👨', HIT: '🥊',
  HOG: '🐗', HOP: '🐰', HOT: '🔥', HOW: '🤔', HUG: '🤗',
  ICE: '🧊', ILL: '🤒', INK: '🖊️', INN: '🏨',
  IVY: '🌿', JAM: '🍯', JAR: '🫙', JAW: '🦷', JET: '✈️',
  JOB: '💼', JOG: '🏃', JOY: '😊',
  JUG: '🫗', KEY: '🔑', KID: '👧', KIT: '🧰', LAB: '🔬',
  LAP: '🏁', LAW: '⚖️', LAY: '🛋️', LED: '💡', LEG: '🦵',
  LET: '👍', LID: '🫙', LIE: '🤥', LIP: '👄', LOG: '🪵',
  LOT: '🎲', LOW: '⬇️', MAD: '😠', MAN: '👨', MAP: '🗺️',
  MAT: '🧶', MAY: '🌸', MEN: '👬', MET: '🤝', MIX: '🥄',
  MOB: '👥', MOM: '👩', MOP: '🧹', MUD: '🟤', MUG: '☕',
  NAP: '😴', NET: '🥅', NEW: '✨', NOD: '👍', NOT: '🚫',
  NOW: '⏰', NUT: '🥜',
  OAK: '🌳', OAR: '🚣', ODD: '🤪', OFF: '📴', OIL: '🛢️',
  OLD: '👴', ONE: '1️⃣', ORB: '🔮',
  OUR: '👥', OUT: '🚪', OWE: '💸', OWL: '🦉', OWN: '🏠',
  PAD: '📝', PAN: '🍳', PAT: '🤚', PAW: '🐾', PAY: '💰',
  PEA: '🫛', PEN: '✒️', PET: '🐶', PIE: '🥧', PIG: '🐷',
  PIN: '📌', PIT: '🕳️', POP: '🎈', POT: '🍲', PUT: '📥',
  RAM: '🐏', RAN: '🏃', RAP: '🎤', RAT: '🐀', RAW: '🥩',
  RAY: '☀️', RED: '🔴', RIB: '🦴', RIG: '🛠️', RIM: '⭕',
  RIP: '💀', ROB: '🦹', ROD: '🎣', ROW: '🚣', RUB: '🧽',
  RUG: '🧶', RUN: '🏃', SAD: '😢', SAT: '🪑', SAW: '🪚',
  SAY: '💬', SEA: '🌊', SET: '📋', SEW: '🧵', SHE: '👩',
  SIP: '🥤', SIT: '🪑', SIX: '6️⃣', SKI: '⛷️', SKY: '🌌',
  SOB: '😭', SON: '👦', SOY: '🫘', SPA: '♨️', SPY: '🕵️',
  SUB: '🥪', SUM: '🔢', SUN: '☀️',
  TAB: '📑', TAG: '🏷️', TAN: '☀️', TAP: '🚿', TAR: '🛣️',
  TAX: '💸', TEA: '🍵', TEN: '🔟', THE: '📖', TIE: '👔',
  TIN: '🥫', TIP: '💡', TOE: '🦶', TON: '⚖️', TOO: '➕',
  TOP: '🔝', TOW: '🚛', TOY: '🧸', TUB: '🛁', TUG: '🚢',
  TWO: '2️⃣', USE: '🔧', VAN: '🚐', VET: '👨‍⚕️', VOW: '💍',
  WAR: '⚔️', WAX: '🕯️', WAY: '🛤️', WEB: '🕸️', WED: '💒',
  WET: '💦', WHO: '🤷', WHY: '❓', WIG: '💇', WIN: '🏆',
  WON: '🥇', WOW: '🤩', YAM: '🍠', YES: '✅', YET: '⏳',
  YOU: '👤', ZAP: '⚡', ZEN: '🧘', ZIP: '🤐', ZOO: '🦁',

  // ── 4-letter words ────────────────────────────────────────────
  ABLE: '💪', ACID: '⚗️', AGED: '🧓', ALSO: '➕', ARCH: '🏛️',
  AREA: '📐', ARMY: '🪖', AWAY: '👋', BABY: '👶', BACK: '🔙',
  BAKE: '🧁', BALL: '⚽', BAND: '🎸', BANK: '🏦', BASE: '🏠',
  BATH: '🛁', BEAR: '🐻', BEAT: '🥁', BEEN: '✅', BELL: '🔔',
  BELT: '🥋', BEND: '↪️', BEST: '🏆', BIRD: '🐦', BITE: '🦷',
  BLOW: '💨', BLUE: '🔵', BOAT: '⛵', BODY: '🫀', BOLD: '💪',
  BOMB: '💣', BOND: '🤝', BONE: '🦴', BOOK: '📖', BOOT: '👢',
  BORN: '👶', BOSS: '👔', BOWL: '🥣', BURN: '🔥', BUSY: '📞',
  CAKE: '🎂', CALL: '📞', CALM: '🧘', CAME: '🚶', CAMP: '🏕️',
  CARD: '🃏', CARE: '❤️', CART: '🛒', CASE: '💼', CASH: '💵',
  CAST: '🎬', CAVE: '🕳️', CHIP: '🍟', CITY: '🏙️', CLAM: '🐚',
  CLAY: '🏺', CLIP: '📎', COAL: '⬛', COAT: '🧥', CODE: '💻',
  COIN: '🪙', COLD: '🥶', COME: '🚶', COOK: '👨‍🍳', COOL: '😎',
  COPE: '🧠', COPY: '📋', CORD: '🔌', CORE: '🔴', CORN: '🌽',
  COST: '💲', COZY: '🛋️', CREW: '👥', CROP: '🌾', CURE: '💊',
  CUTE: '🥰', DARE: '😈', DARK: '🌑', DATA: '📊', DATE: '📆',
  DAWN: '🌅', DEAL: '🤝', DEAR: '💌', DECK: '🃏', DEEP: '🌊',
  DEER: '🦌', DESK: '🪑', DIAL: '📞', DICE: '🎲', DIET: '🥗',
  DIRT: '🟤', DISH: '🍲', DISK: '💿', DOCK: '⚓', DOES: '✅',
  DONE: '✅', DOOR: '🚪', DOSE: '💊', DOWN: '⬇️', DRAW: '✏️',
  DREW: '✏️', DROP: '💧', DRUM: '🥁', DUAL: '👯', DUCK: '🦆',
  DUEL: '⚔️', DULL: '😐', DUMB: '🤐', DUMP: '🗑️', DUST: '✨',
  DUTY: '🎖️', EACH: '👆', EARN: '💰', EASE: '😌', EAST: '🧭',
  EASY: '😄', EDGE: '🔪', ELSE: '🔀', EPIC: '🔥', EVEN: '⚖️',
  EVER: '♾️', EVIL: '😈', EXAM: '📝', FACE: '😀', FACT: '📊',
  FADE: '🌫️', FAIL: '❌', FAIR: '🎪', FALL: '🍂', FAME: '⭐',
  FARM: '🚜', FAST: '💨', FATE: '🔮', FEAR: '😨', FEED: '🍼',
  FEEL: '🫶', FEET: '🦶', FELL: '⬇️', FELT: '🤚', FILE: '📁',
  FILL: '🫗', FILM: '🎬', FIND: '🔍', FINE: '👌', FIRE: '🔥',
  FIRM: '🏢', FISH: '🐟', FLAG: '🏳️', FLAT: '🏠', FLEW: '✈️',
  FLIP: '🔄', FLOW: '🌊', FOAM: '🫧', FOLD: '📂', FOLK: '🎻',
  FOOD: '🍔', FOOL: '🤡', FOOT: '🦶', FORD: '🚗', FORK: '🍴',
  FORM: '📋', FORT: '🏰', FOUL: '🟡', FOUR: '4️⃣', FREE: '🦅',
  FROM: '📤', FUEL: '⛽', FULL: '💯', FUND: '💰', FURY: '😤',
  FUSE: '💥', GAIN: '📈', GAME: '🎮', GANG: '👥', GATE: '🚪',
  GAVE: '🎁', GAZE: '👀', GEAR: '⚙️', GIFT: '🎁', GIRL: '👧',
  GIVE: '🎁', GLAD: '😊', GLOW: '✨', GLUE: '🧴', GOAT: '🐐',
  GOES: '🚶', GOLD: '🥇', GOLF: '⛳', GONE: '👋', GOOD: '👍',
  GRAB: '🤲', GRAY: '🩶', GREW: '🌱', GRID: '📊', GRIN: '😁',
  GRIP: '🤝', GROW: '🌱', GULF: '🌊',

  // ── 5-letter words ────────────────────────────────────────────
  ABOVE: '⬆️', ADMIT: '🙋', ADOPT: '🤱', AGENT: '🕵️', AGREE: '🤝',
  AHEAD: '⏩', ALARM: '🚨', ALBUM: '📀', ALIGN: '📐', ALIVE: '💚',
  ALLOW: '✅', ALONE: '🧍', ALONG: '➡️', ALTER: '🔄', AMONG: '👥',
  ANGEL: '👼', ANGER: '😠', ANGLE: '📐', APART: '↔️', APPLE: '🍎',
  ARENA: '🏟️', ARISE: '🌅', ARMOR: '🛡️', ARRAY: '📊', ASIDE: '👉',
  ASSET: '💎', AVOID: '🚫', AWARD: '🏅', AWARE: '👁️', BASIC: '📌',
  BEACH: '🏖️', BEGIN: '▶️', BEING: '🧬', BELOW: '⬇️', BENCH: '🪑',
  BLACK: '⬛', BLADE: '🗡️', BLAME: '👉', BLANK: '⬜', BLAST: '💥',
  BLAZE: '🔥', BLEED: '🩸', BLEND: '🧃', BLIND: '🦯', BLOCK: '🧱',
  BLOOM: '🌸', BLOWN: '💨', BOARD: '📋', BONUS: '🎁', BOUND: '🔗',
  BRAIN: '🧠', BRAND: '™️', BRAVE: '⚔️', BREAD: '🍞', BREAK: '💔',
  BREED: '🐾', BRICK: '🧱', BRIEF: '📝', BRING: '🤲', BROAD: '↔️',
  BROWN: '🟤', BRUSH: '🖌️', BUILD: '🏗️', BURST: '💥',
  CABIN: '🛖', CABLE: '🔌', CHAIN: '⛓️', CHAIR: '🪑', CHARM: '✨',
  CHASE: '🏃', CHEAP: '💲', CHECK: '✅', CHESS: '♟️', CHIEF: '👑',
  CHILD: '👧', CIVIC: '🏛️', CLAIM: '📜', CLASS: '🏫', CLEAN: '🧹',
  CLEAR: '💎', CLIMB: '🧗', CLING: '🤝', CLOCK: '🕐', CLONE: '👯',
  CLOSE: '🚪', CLOUD: '☁️', COACH: '📋', COAST: '🏖️', CORAL: '🪸',
  COULD: '🤔', COUNT: '🔢', COURT: '⚖️', COVER: '📕', CRACK: '💥',
  CRAFT: '🔨', CRANE: '🏗️', CRASH: '💥', CRAZY: '🤪', CREAM: '🍦',
  CRIME: '🔍', CROSS: '✝️', CROWD: '👥', CROWN: '👑', CRUSH: '💘',
  CURVE: '〰️', CYCLE: '🚲', DAILY: '📅', DANCE: '💃', DEATH: '💀',
  DEBUT: '🌟', DELAY: '⏳', DELTA: '🔺', DENSE: '🌳', DEPTH: '🌊',
  DEVIL: '😈', DIARY: '📔', DIRTY: '🟤', DIZZY: '😵', DOUBT: '🤔',
  DRAFT: '📝', DRAIN: '🚿', DRAKE: '🦆', DRAMA: '🎭', DRANK: '🥤',
  DRAWN: '✏️', DREAM: '💭', DRESS: '👗', DRIED: '☀️', DRIFT: '🌊',
  DRILL: '🔩', DRINK: '🥤', DRIVE: '🚗', DROWN: '🌊',

  // ── 6-letter words ────────────────────────────────────────────
  ABSORB: '🧽', ACCESS: '🔓', ACROSS: '↔️', ACTION: '🎬', ACTIVE: '🏃',
  ADJUST: '🔧', ADMIRE: '😍', ADVENT: '🌟', AFFORD: '💰', AGENDA: '📋',
  ALMOST: '🤏', ALWAYS: '♾️', AMOUNT: '🔢', ANCHOR: '⚓', ANIMAL: '🐾',
  ANNUAL: '📅', ANSWER: '💬', APPEAL: '📢', APPEAR: '👀', ARRIVE: '🚶',
  ARTIST: '🎨', ATTACH: '📎', ATTACK: '⚔️', ATTEND: '🧑‍🤝‍🧑', AUGUST: '☀️',
  BATTLE: '⚔️', BEAUTY: '💎', BECOME: '🦋', BEFORE: '⏪', BEHIND: '🔙',
  BELONG: '🏠', BESIDE: '↔️', BETTER: '📈', BEYOND: '🚀', BITTER: '😖',
  BLANCH: '🍳', BORDER: '🗺️', BORROW: '🤲', BOTTLE: '🍾', BOTTOM: '⬇️',
  BOUNCE: '🏀', BRANCH: '🌿', BREATH: '💨', BRIDGE: '🌉', BRIGHT: '💡',
  BROKEN: '💔', BRONZE: '🥉', BROWSE: '🔍', BUBBLE: '🫧', BUDGET: '💰',
  BUNDLE: '📦', BURDEN: '🏋️', BUREAU: '🏢', BUTTER: '🧈', BUTTON: '🔘',
  CAMERA: '📷', CANCEL: '❌', CANDLE: '🕯️', CARBON: '⚫', CARPET: '🧶',
  CASTLE: '🏰', CAUGHT: '🫴', CENTER: '🎯', CHANCE: '🎲', CHANGE: '🔄',
  CHARGE: '🔋', CHOICE: '🤔', CHOOSE: '👆', CIRCLE: '⭕', CLEVER: '🧠',
  CLIENT: '🧑‍💼', CLOSED: '🔒', CLOSET: '🚪', COFFEE: '☕', COLUMN: '🏛️',
  COMBAT: '⚔️', CORNER: '📐', COSMIC: '🌌', COTTON: '☁️', COUPLE: '💑',
  COURSE: '📚', CREATE: '🎨', CREDIT: '💳', CRISIS: '🚨', CUSTOM: '🎨',
  DAMAGE: '💥', DANGER: '⚠️', DEBATE: '🗣️', DECADE: '🔟', DECIDE: '✅',
  DEFEAT: '😞', DEFEND: '🛡️', DEFINE: '📖', DEGREE: '🎓', DEMAND: '📢',
  DENIAL: '🚫', DEPEND: '🔗', DEPLOY: '🚀', DESERT: '🏜️', DESIGN: '🎨',
  DESIRE: '❤️', DETAIL: '🔍', DETECT: '🕵️', DEVICE: '📱', DEVOTE: '❤️',
  DIALOG: '💬', DIFFER: '↔️', DINNER: '🍽️', DIRECT: '➡️', DIVIDE: '➗',
  DOCTOR: '👨‍⚕️', DOMAIN: '🌐', DONATE: '🎁', DOUBLE: '✌️', DRAGON: '🐉',
  DRIVEN: '🚗',

  // ── 7+ letter words ───────────────────────────────────────────
  ABANDON: '🏚️', ABILITY: '💪', ABSENCE: '👻', ABSOLVE: '🙏', ACADEMY: '🏫',
  ACHIEVE: '🏆', ACQUIRE: '🤲', ADDRESS: '📍', ADVANCE: '⏩', ALREADY: '⏰',
  ANCIENT: '🏛️', ANOTHER: '🔄', ANXIETY: '😰', BALANCE: '⚖️', BANKING: '🏦',
  BARRIER: '🧱', BATTERY: '🔋', BETWEEN: '↔️', BILLION: '💰', CABINET: '🗄️',
  CALCIUM: '🦴', CAPABLE: '💪', CAPITAL: '🏛️', CAPTURE: '📸', CAREFUL: '⚠️',
  CATALOG: '📚', CENTRAL: '🎯', CERTAIN: '✅', CHAMBER: '🏛️', CHANNEL: '📺',
  CHAPTER: '📖', CHICKEN: '🐔', CLASSIC: '🏆', CLIMATE: '🌍', CLOSURE: '🔒',
  CLUSTER: '🍇', COASTAL: '🏖️', COLLECT: '🧺', COMBINE: '🔗', COMMAND: '📢',
  COMMENT: '💬', COMPACT: '📦', COMPANY: '🏢', COMPARE: '⚖️', COMPETE: '🏁',
  COMPLEX: '🧩', CONCERN: '😟', CONDUCT: '🎵', CONFIRM: '✅', CONNECT: '🔗',
  CONTAIN: '📦', CONTENT: '😊', CONTEXT: '📖', CONTROL: '🎛️', CONVERT: '🔄',
  CORRECT: '✅', COUNTER: '🔢', COUNTRY: '🏞️', COURAGE: '🦁', CREATOR: '🎨',
  CRICKET: '🏏', CRYSTAL: '💎', CULTURE: '🎭', CURRENT: '⚡', CUSHION: '🛋️',
  DIAMOND: '💎', DIGITAL: '💻', DISPLAY: '🖥️', DISTANT: '🔭', DIVERSE: '🌈',
  DOLPHIN: '🐬', EASTERN: '🧭', ECONOMY: '📈', EDITION: '📰', EDUCATE: '📚',
  ELECTED: '🗳️', ELEMENT: '⚛️', EMOTION: '😊', ENDLESS: '♾️', ENTROPY: '🌀',
  EPISODE: '📺', ESSENCE: '✨', ETERNAL: '♾️', EVENING: '🌆', EVIDENT: '👁️',
  EXAMINE: '🔬', EXAMPLE: '📌', EXCITED: '🎉', EXECUTE: '▶️', EXHIBIT: '🖼️',
  EXPLAIN: '💡', EXPLORE: '🧭', EXPRESS: '🚄', EXTREME: '🔥', FACTORY: '🏭',
  FAILURE: '❌', FASHION: '👗', FEATURE: '⭐', FICTION: '📚', FIFTEEN: '🔢',
  FINALLY: '🏁', FINANCE: '💰', FISHING: '🎣', FITNESS: '🏋️', FOREIGN: '🌍',
  FOREVER: '♾️', FORTUNE: '🍀', FORWARD: '⏩', FOUNDER: '🧑‍💼', FREEDOM: '🦅',
  GALLERY: '🖼️', GATEWAY: '🚪', GENERAL: '⭐', GENUINE: '💎', GLACIER: '🏔️',
  GROCERY: '🛒', HABITAT: '🏡', HALFWAY: '↔️', HANDFUL: '🤏', HEALTHY: '💚',
  HIGHWAY: '🛣️', HISTORY: '📜', HOLIDAY: '🏖️', HORIZON: '🌅', HUNDRED: '💯',
  IMAGINE: '💭', INCLUDE: '📥', INITIAL: '🔤', INQUIRY: '❓', INSPECT: '🔍',
  INSTALL: '🔧', INSTEAD: '🔄', INTENSE: '🔥', INVOLVE: '🤝', JOURNAL: '📓',
  KITCHEN: '🍳', LANDING: '✈️', LASTING: '♾️', LEADING: '🥇', LEATHER: '🧥',
  LECTURE: '🎓', LIBERAL: '🗽', LIBRARY: '📚', LIMITED: '🚫', LOCATED: '📍',
  LOGICAL: '🧠', MACHINE: '⚙️', MANAGER: '👔', MASSIVE: '🏔️', MEDICAL: '🏥',
  MILLION: '💰', MINERAL: '💎', MIRACLE: '✨', MISSION: '🚀', MIXTURE: '🧪',
  MONITOR: '🖥️', MONSTER: '👹', MORNING: '🌅', MYSTERY: '🔮', NATURAL: '🌿',
  NETWORK: '🌐', NEUTRAL: '⚖️', NOTABLE: '⭐', NOTHING: '🕳️', NUCLEAR: '☢️',
  OBVIOUS: '👀', OPENING: '🚪', OPINION: '💬', ORGANIC: '🌿', OUTDOOR: '🏕️',
  OUTLINE: '✏️', OVERALL: '📊', PACKAGE: '📦', PADDING: '🛋️', PASSAGE: '🚶',
  PATIENT: '🏥', PATTERN: '🔲', PAYMENT: '💳', PENALTY: '🟡', PERFECT: '💯',
  PERFORM: '🎭', PIONEER: '🚀', PLASTIC: '♻️', PLASTER: '🏥', PLAYFUL: '🎈',
  PLEASED: '😊', POPULAR: '⭐', PORTION: '🍕', POTTERY: '🏺', POVERTY: '📉',
  PRECISE: '🎯', PREDICT: '🔮', PREMIER: '🏆', PREMIUM: '💎', PREPARE: '📝',
  PRESENT: '🎁', PREVENT: '🛑', PRIMARY: '1️⃣', PRIVACY: '🔒', PROBLEM: '🧩',
  PROCEED: '▶️', PRODUCE: '🌽', PRODUCT: '📦', PROFILE: '👤', PROGRAM: '💻',
  PROJECT: '📋', PROMISE: '🤞', PROMOTE: '📢', PROTECT: '🛡️', PROTEIN: '🥩',
  PROTEST: '✊', PROVIDE: '🤲', PUBLISH: '📰', PURPOSE: '🎯', PURSUIT: '🏃',
  QUALITY: '⭐', QUARTER: '🪙', RADICAL: '💥', RAINBOW: '🌈', READING: '📖',
  REALITY: '🌍', RECEIVE: '📬', RECOVER: '💚', REFLECT: '🪞', REGULAR: '📏',
  RELATED: '🔗', RELEASE: '🎬', REMAINS: '🏚️', REMOVAL: '🗑️', RENEWAL: '🔄',
  REPLACE: '🔄', REPLICA: '👯', REQUEST: '📩', REQUIRE: '📋', RESERVE: '🏞️',
  RESOLVE: '💪', RESPECT: '🫡', RESTORE: '🔧', RETIRED: '🧓', RETREAT: '🏖️',
  REVERSE: '⏪', ROUTINE: '📅', RUNNING: '🏃', SAILING: '⛵', SCHOLAR: '🎓',
  SCIENCE: '🔬', SECTION: '📑', SHELTER: '🏠', SILENCE: '🤫', SIMILAR: '👯',
  SIXTEEN: '🔢', SKILLED: '🏅', SLAVERY: '⛓️', SOCIETY: '🌍', SOLDIER: '🪖',
  SOMEHOW: '🤷', SPEAKER: '🎤', SPECIAL: '⭐', STORAGE: '📦', STUDENT: '🎓',
  SUBJECT: '📚', SUCCESS: '🏆', SUPPORT: '🤝', SUPREME: '👑', SURFACE: '🌊',
  SURGEON: '👨‍⚕️', SURVIVE: '💪', TEACHER: '👩‍🏫', TENSION: '😬', THERAPY: '🧘',
  THOUGHT: '💭', TONIGHT: '🌙', TOURIST: '🧳', TRAFFIC: '🚦', TROUBLE: '⚠️',
  TURNING: '🔄', TYPICAL: '📌', UNIFORM: '👔', UNKNOWN: '❓', UPGRADE: '⬆️',
  VARIETY: '🌈', VENTURE: '🚀', VERSION: '📋', VETERAN: '🎖️', VICTORY: '🏆',
  VILLAGE: '🏘️', VIOLENT: '💥', VISIBLE: '👁️', WARRIOR: '⚔️', WEATHER: '🌤️',
  WEBSITE: '🌐', WELCOME: '👋', WESTERN: '🤠', WHISPER: '🤫', WILLING: '👍',
  WINNING: '🏆', WITNESS: '👁️', WORKOUT: '🏋️', WRITING: '✍️',
};

export function getWordEmoji(word: string): string {
  return WORD_EMOJI_MAP[word.toUpperCase()] || '🔤';
}
